### ISSUE TITLE
Improve intelligence of multithreading

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/npgamma#10]
There will be a point where the number of points being calculated will be slower if it undergoes a split across 4 threads. I need to determine when numpy is faster to not split.

Also, the split happens for every distance. This constant splitting and rejoininng has threads often waiting for others to catch up.

A smarter way would be to divy up evaluation points at the very beginning. Do them in completely separate processes throughout. Merge the gamma results at the end. This would result in far cleaner code also.

**Comment by AlainSottiaux** [comment]
I confirm your observations:
With version 0.6.0, I tested with 4 cores (out of 12), with approximately 20% increase in performance regarding the 1 core version. With 12 cores, execution time was the double than with 4.

**Comment by SimonBiggs** [comment]
Execution took longer when using 12 cores?  I'll see if I can do a bit more
work on it. I think I can improve how I've done the multiprocessing.

**Comment by SimonBiggs** [comment]
Hi @AlainSottiaux,

I have just implemented multithreading in an alternative way. This new multithreading method is released with npgamma 0.6.1 which is currently available on pypi. I would be keen to hear if 12 cores provides an improvement now with this new method.

Cheers,
Simon

**Comment by AlainSottiaux** [comment]
Hi @SimonBiggs ,
I made some tests comparing multithreading performance from 0.6.0 to 0.6.1 version. I call many times the gamma calculation, randomly choosing the number of threads ( from 1 to 12, the max number of cores on my virtual workstation).
![npgamma_mt_perf](https://cloud.githubusercontent.com/assets/3470371/22456620/de5cfb06-e793-11e6-984b-0a9baa6d588e.png)
With 0.6.0, even with 2 threads, the performance improvement was not so big, and the performance degraded when increasing the number of threads. The CPU usage was not constant (you already mentionned that the multiple thread spent time to wait each other)
It looks better with 0.6.1! CPU usage is near the maximum of a core all the time. We can observe a "ramp up" of Cpu usage (an additionnal thread every second) when starting the calculation, and a similar cool down at the end. Using 4 or 5 threads is approximately 4 times faster than with 1 thread of version 0.6.0.

Cheers
Alain

**Comment by SimonBiggs** [comment]
Thanks for that. I appreciate it. It's good to see the improvement. Unfortunate that after 5 cores there is next to no improvement. But it is nice to see it working as expected.

The next version will likely run a bit slower again as there is something extra I want to implement to improve calculation accuracy. Might be a version 0.7.0 in a week or so which would be interesting to see what the performance hit is.
