### ISSUE TITLE
Differing grid sizes

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/npgamma#5]
Hi Simon, this looks like it could be very useful for a project I am working on, comparing the doses calculated with AAA/AXB in Eclipse. I have some working code for 3D gamma analysis (below, credit to J.Kerns) but have not thoroughly tested it yet. One of the issues I encountered is that the grid sizes is slightly different for AAA/AXB (see In [29]). In my code I get around this by simply cropping the larger grid. However I wonder if you have code for placing two dose cubes onto the same grid, or if the gamma analysis code account for this?
Cheers
Robin

https://github.com/robmarkcole/Useful-python-for-medical-physics/blob/master/Experiments%20in%20ipython%20notebooks/dicompyler-core%20experiments/AXB%20project/Lung%20plan%2030%20exported%2011-10-2016/Case_30%20Lung%20PTV%2031-10-2016.ipynb

**Comment by SimonBiggs** [comment]
Hi Robin,

npgamma can take arbitrary differing grid sizes for reference and evaluation. The way it works is a bilinear interpolation function is created of the reference grid early on in the process. The gamma is calculated for each evaluation point compared to the reference interpolation function. The resulting gamma grid size matches that of the evaluation grid. 

If you would like any further clarification let me know.

This code base is also in need of validation so step carefully here also. If you do find it useful and put it through validation please keep me in the loop.

Cheers,
Simon

**Comment by robmarkcole** [comment]
> Exception: Length of items in coords_reference does not match the shape of dose_reference

Hi Simon, I am getting this error, although I expected the differing grid resolutions not to be a problem in v5.2 ..?
Cheers

https://github.com/robmarkcole/Useful-python-for-medical-physics/blob/master/Experiments%20in%20ipython%20notebooks/Project/Robin%20HN%2021-11-2016/Case7%2028-11-2016/Analyse%20case7%20npgamma%2028-11-2016.ipynb

**Comment by SimonBiggs** [comment]
That's saying that the reference coords don't match the reference dose
shape. The issue is most likely to do with the order of x and y. The order
used to be (y, x, z) to match matplotlib. But especially when I made the
code dimensionally independent that became difficult to maintain. So now
the order is (x, y, z).

I should put a check in there to see if x and y are swapped around, if they
are, have the error say x and y are swapped around, instead of the error
you got. It would be more informative that way.

Potentially there could be a disagreement with the dicom loading code given
at the top of the notebook. I've just got my hands on a dicom file with
differing x and y sizes for the very purpose of checking the dicom loading
code. I shall have a check of that this evening. That very well could be
the issue.

**Comment by SimonBiggs** [comment]
Something to check is to write np.shape(dose_reference) and then compare
that to len(x_reference), len(y_reference), and len(z_reference).

**Comment by robmarkcole** [comment]
![image](https://cloud.githubusercontent.com/assets/11855322/20703451/906be76a-b613-11e6-9be8-6fda6f852463.png)

**Comment by SimonBiggs** [comment]
So I have updated the dicom reading functions. And given that the dose is being read in matplotlib format (dose[y, x, z]) when inputting the coordinates into npgamma they need to be in the order (y, x, z).

I have fixed the notebook documentation, and I have put comments within the dicom loading functions highlighting where they may have issues.

https://github.com/SimonBiggs/npgamma/blob/master/Module%20usage%203D.ipynb

Hope this helps. Sorry for all the confusion.

**Comment by SimonBiggs** [comment]
Here is a blog post describing the x, y swap confusion:
http://eli.thegreenplace.net/2014/meshgrids-and-disambiguating-rows-and-columns-from-cartesian-coordinates/

**Comment by robmarkcole** [comment]
Hi Simon, thanks for the quick response, this is working nicely now.
Next question, is it possible some way to overlay the outline of structures on each slice?
Thanks
Robin

https://github.com/robmarkcole/Useful-python-for-medical-physics/blob/master/Experiments%20in%20ipython%20notebooks/Project/Robin%20HN%2021-11-2016/Case7%2028-11-2016/Analyse%20case7%20npgamma%2029-11-2016.ipynb

**Comment by SimonBiggs** [comment]
Yes it definitely is. I achieved that specific task in some code I have saved at work. However I have attached a similar bit of code which can be adapted to the task if you need it. I'm back at work on Thursday, I'll see if I can find the contour overlay code then. Until then, see if the attached code helps.

Cheers,
Simon

[021+Structures+test.html.zip](https://github.com/SimonBiggs/npgamma/files/619020/021.Structures.test.html.zip)

**Comment by robmarkcole** [comment]
That code works for me, looks like a promising start. Cheers!

**Comment by SimonBiggs** [comment]
You're welcome :)

**Comment by robmarkcole** [comment]
![image](https://cloud.githubusercontent.com/assets/11855322/20712462/015eb84e-b63c-11e6-9db8-b76df9227760.png)

**Comment by robmarkcole** [comment]
Something like that with gamma would be awesome!

**Comment by SimonBiggs** [comment]
Are you able to send me an email at mail@simonbiggs.net. I have a manuscript I would like to send to you. You might find it useful.
