### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/npgamma#6]
Hi Simon, I get a memory error in Method explanation 3D at Ln [10] but am able to continue.

https://github.com/robmarkcole/Useful-python-for-medical-physics/blob/master/Experiments%20in%20ipython%20notebooks/npgamma/test/Method%20explanation%203D%20_%20RC.ipynb

I get the same error in Module usage 3D at ln[9] but am unable to continue. Please advise :)

https://github.com/robmarkcole/Useful-python-for-medical-physics/blob/master/Experiments%20in%20ipython%20notebooks/npgamma/test/Module%20usage%203D%20_%20RC.ipynb

**Comment by SimonBiggs** [comment]
Thanks for letting me know. I'll have a look. Out of interest how much RAM do you have on the computer running the program?

**Comment by robmarkcole** [comment]
4 Gb (3.17 usable). However the OS (Win 7 SP 1) is 32 bit and my understanding is that this may restrict RAM further.

**Comment by SimonBiggs** [comment]
Are you able to set the parameter maximum_test_distance=6 and let me know how it goes. In the most recent release I removed the default behaviour of that parameter.

**Comment by SimonBiggs** [comment]
I was considering putting in a RAM parameter for the purpose of limiting having the code slow down and use less RAM if it is requested to. Unfortunately it wouldn't be simple, but it might be worthwhile...

**Comment by robmarkcole** [comment]
With maximum_test_distance=6  same error :-(

**Comment by SimonBiggs** [comment]
It won't be as accurate, but could you try distance_step_size=1 ? Just trying to reduce the amount of RAM the code will use.

**Comment by robmarkcole** [comment]
same error unfortunately

**Comment by SimonBiggs** [comment]
Hi Rob,

Yes I can confirm. The most recent release is using way too much RAM. I'll have to have a look into it. For now, if you use the following code base:
https://github.com/SimonBiggs/npgamma/tree/d7de93fb619a87b58d00d4b988faed6dbcf117f1

Or install npgamma with:
pip install npgamma==0.4.3

I'll see if I can get some time tonight to look into it. Thanks for letting me know.

**Comment by SimonBiggs** [comment]
Hi Robin,

It was unfortunately a more sinister error. When I generalised my code to work for any of the three dimensions I didn't provide the correct indexing parameter to meshgrid. Unfortunately I didn't pick this up with my unit tests and I didn't rerun the notebooks.

The latest release (https://github.com/SimonBiggs/npgamma/releases/tag/0.5.1 and pip install npgamma==0.5.1) has this fixed. Please let me know if you have any further troubles.

**Comment by robmarkcole** [comment]
Sadly still getting the error 

https://github.com/robmarkcole/Useful-python-for-medical-physics/blob/master/Experiments%20in%20ipython%20notebooks/npgamma/test/Module%20usage%203D%20_%20RC.ipynb

**Comment by SimonBiggs** [comment]
I guess that's the problem when the computer I build this on has 16GB of RAM. To make this more widely usable I do need to put in a RAM limiting option. 

Out of interest does the 2D example work?

**Comment by SimonBiggs** [comment]
I'll see if I get a chance to work on this tonight. I'm in Australia, so about 12 hour from now I think the first thing I need to do is create a means for visual feedback on its process. That way we can see how far along your code gets before it brakes. Then we can use that to inform me if I should implement the upper limit on RAM usage.

**Comment by robmarkcole** [comment]
OK Module usage 3D, calc_gamma(), maximum_test_distance = distance_threshold * 2,  is working on my macbook air with 8GB Ram. Will test the 2D at work PC

**Comment by SimonBiggs** [comment]
Thanks for the update. It does highlight that I need the program to handle
running out of RAM in a sensible manner.

Initially I think I'll just create a "splitter" parameter or something of
the sort. It would recieve a number >= 1 and will divide the evaluation
array up into portions to be completed one after the other. This will
result in slower computation but less RAM usage.

Once the splitter idea works then I can have the program recieve a max_ram
parameter and it will just assign a splitter value appropriately. It might
need to dynamically determine the splitter value before each iteration as
subsequent iterations use more RAM if a small enough gamma has not yet been
found.

Finally I could use psutil (http://pythonhosted.org/psutil/) as an optional
dependency. It would call psutil to find out how much RAM is installed on
the system and then it would leave 2GB for the OS and use the remaining RAM
as the default input into the max_ram parameter.

Does that sound like it might be easy enough to use?

**Comment by robmarkcole** [comment]
Yes sounds like a good approach. 
Running on my mac

import psutil
mem = psutil.virtual_memory()
mem

svmem(total=8589934592, available=3261071360, percent=62.0, used=8046948352, free=139493376, active=3223863296, inactive=3121577984, wired=1701507072)

I am surprised how little memory is available.!

**Comment by SimonBiggs** [comment]
From the little I understand "Available" is not always a good proxy for how
much to use. If a program asks for a large amount of RAM the OS will often
reassign RAM appropriately anyway. I think that's why the Total - 2GB might
be the best way to go.

Also, I need to somehow check for 32bit or 64 bit using:
is_64bits = sys.maxsize > 2**32

If it is 32bit any one program can only every use a maximum of 2GB of RAM.
So no matter how much is available I would have to have 2GB as the max.

**Comment by robmarkcole** [comment]
Module usage 2D works on my work PC...
Also svmem(total=3409248256, available=608727040, percent=82.1, used=2800521216, free=608727040)

**Comment by SimonBiggs** [comment]
Alright, so I'll see if I get a chance tonight to implement some RAM
limiting features. That should help you be able to use it at work. (At the
cost of calculation time).

**Comment by SimonBiggs** [comment]
So I have just released a new version (0.5.2). This implements a new
parameter within gamma_calc called "max_concurrent_calc_points". In the
demonstration notebook the use of this parameter is outlined:
https://github.com/SimonBiggs/npgamma/blob/master/Module%20usage%203D.ipynb

I would be quite keen to hear the results of you running the updated
notebook for npgamma 0.5.2 on your 32 bit python.

Cheers,
Simon

**Comment by robmarkcole** [comment]
Working on my 32 bit pc now, cheers!

**Comment by SimonBiggs** [comment]
You're welcome :). I would be very keen to hear the results of any
validation this code undergoes that is independent from myself.
